dhis2/line-listing-app

- src/components/Dialogs/Conditions/ConditionsManager.js
- src/components/Dialogs/DynamicDimension.js
- yarn.lock
Implements [TECH-1022](https://jira.dhis2.org/browse/TECH-1022)
Moves the debug info from the modal title to the console
> chore: move debug info to console.log

- src/components/Visualization/Visualization.js
Implements [TECH-1008](https://jira.dhis2.org/browse/TECH-1008)
---
1. format date dimensions
---
All dimensions with `valueType` equal to `DATE` show the value with `yyyy-MM-DD` format.
`lastUpdated` shows the time in addition (hh:mm).
---
> fix: format date values (TECH-1008)

- src/components/MainSidebar/DimensionItem/DimensionItemBase.module.css
- src/components/MainSidebar/MainSidebarSection.module.css
- Removing some space from main/time dimensions sections
- Removing bold text for selected items
- Removes green text for selected items
Ref spec:
> fix: adjust css for main/time dimensions and chips according to spec

- package.json
- yarn.lock
Implements [TECH-1021](https://jira.dhis2.org/browse/TECH-1021)
**Requires https://github.com/dhis2/analytics/pull/1168**
---
1. Bumps Analytics to latest
---
> fix: add to layout button for line list (TECH-1021)

- src/components/Layout/DefaultLayout/styles/DefaultAxis.module.css
- src/components/Layout/styles/Chip.module.css
Implements [TECH-1031](https://dhis2.atlassian.net/browse/TECH-1031)
---
https://user-images.githubusercontent.com/6113918/157646591-71cdca58-119f-4a0c-b520-0bc25b82f414.mov
> fix: set pointer cursor on the chip directly to avoid pointer over drop zones

- i18n/en.pot
- src/components/MainSidebar/InputPanel/InputPanel.js
- src/modules/visualization.js
Updates input description. Removes unused duplication.
> fix: input description

- src/components/Visualization/StartScreen.js
> fix: don't call hooks conditionally

- i18n/en.pot
- src/components/MainSidebar/ProgramDimensionsPanel/ProgramDimensionsFilter.js
Implements [TECH-1043](https://dhis2.atlassian.net/browse/TECH-1043)
After:
---
> fix: add cat and cogs filters (TECH-1043)

- src/components/Interpretations/common/RichTextEditor/RichTextEditor.js
- src/components/Interpretations/common/RichTextEditor/styles/RichTextEditor.style.js
Implements [TECH-1048](https://dhis2.atlassian.net/browse/TECH-1048)
---
1. fix vertical alignment of toolbar buttons
---
Before:
After:
> fix: align vertically toolbar buttons TECH-1048

- src/components/Visualization/Visualization.js
Implements [TECH-1065](https://dhis2.atlassian.net/browse/TECH-1065)
---
1. fix check for opening dialog on most recent header
---
The most recent header has `0` for `stageOffset`.
The condition must include `0` as true value, so a simple `if` or ternary condition doesn't work.
Use `isNaN` instead.
> fix: open modal for most recent header TECH-1065

- package.json
- yarn.lock
Implements [TECH-1063](https://dhis2.atlassian.net/browse/TECH-1063)
Related fix: https://github.com/dhis2/analytics/pull/1191
> fix: upgrade analytics

- i18n/en.pot
- package.json
- src/components/Interpretations/InterpretationModal/CommentAddForm.js
- src/components/Interpretations/InterpretationModal/InterpretationModal.js
- src/components/Interpretations/InterpretationsUnit/InterpretationForm.js
- src/components/Interpretations/InterpretationsUnit/InterpretationList.js
- src/components/Interpretations/common/Interpretation/Interpretation.js
- src/components/Interpretations/common/Interpretation/InterpretationUpdateForm.js
- src/components/Interpretations/common/Message/Message.js
- src/components/Interpretations/common/UserMention/useUserSearchResults.js
- yarn.lock
Implements [TECH-1055](https://dhis2.atlassian.net/browse/TECH-1055)
---
1. add sharing icon in Interpretation toolbar
2. sort interpretations within a date in descending order
3. “Write a reply” instead of “Add a comment”
4. “Post reply” instead of “Save comment”
5. fix mentioning api request
6. spacing between interpretations thread and right margin
---
1. Interpretations sorted descending:
2. Sharing icon:
3. 4. Write a reply/Post reply:
5. User lookup request:
6. Right spacing:
> fix: interpretations fixes TECH-1055

- package.json
- src/actions/current.js
- src/components/DownloadMenu/useDownloadMenu.js
- src/components/Visualization/Visualization.js
- src/reducers/ui.js
- yarn.lock
Implements [TECH-1050](https://dhis2.atlassian.net/browse/TECH-1050)
---
1. pass missing parameters to download URL
---
Needs testing, but at least now I don't get 500.
The page/pageSize is needed for this to work until the `paging=false` is supported in the api.
---
-   [x] remove page/pageSize and pass `paging=false` instead when the backend is fixed
---
Example request with page/pageSize and sorting:
http://localhost:8080/api/analytics/enrollments/query/yDuAzyqYABS.json?dimension=ou%3AFV43JisquSm&dimension=a1jCssI2LkW.rWYryQb3ohn&outputType=ENROLLMENT&outputIdScheme=UID&enrollmentDate=LAST_12_MONTHS&programStatus=ACTIVE&headers=enrollmentdate%2Couname%2Ca1jCssI2LkW.rWYryQb3ohn%2Cprogramstatus&page=2&pageSize=30&asc=enrollmentdate
("A1 download 1" on tracker_dev)
> fix: download url

- package.json
- src/components/Visualization/Visualization.js
- yarn.lock
Implements [TECH-1081](https://dhis2.atlassian.net/browse/TECH-1081)
Addresses [LIBS-308](https://dhis2.atlassian.net/browse/LIBS-308)
---
1. reset page when page size is changed
2. Solve the issue with the "jumping page range".
---
All pager information is now fed to the `Pagination` component from the analytics response.
---
Video showing both the page reset when page size is changed, and the page range shown correctly for different pages:
https://user-images.githubusercontent.com/150978/162932527-541b1049-edb0-49ca-82b1-ccfc775d0681.mov
> fix: reset page when changing page size TECH-1081

- src/modules/visualization.js
Implements [TECH-1090](https://dhis2.atlassian.net/browse/TECH-1090)
Filters out longitude and latitude dimensions immediately after load.
> fix: filter out longitude and latitude dimensions (TECH-1090)

- src/components/Dialogs/PeriodDimension/PeriodDimension.js
- src/reducers/settings.js
Implements [TECH-1080](https://dhis2.atlassian.net/browse/TECH-1080)
---
1. add property `excludedPeriodTypes` for PeriodDimension
---
https://user-images.githubusercontent.com/6113918/164001964-b3669483-2f91-44dd-bd6a-eae07135993b.mov
> fix: respect system settings regarding hidden periods

- src/components/Layout/styles/Chip.module.css
> fix: add missing padding to chip

- src/components/App.js
---
1. no functional changes. Simply switching to consistent use of useDispatch and useSelector
> refactor: switch from connect to useSelector and useDispatch in App component

- src/components/MainSidebar/ProgramDimensionsPanel/ProgramDimensionsFilter.js
- src/components/MainSidebar/YourDimensionsPanel/YourDimensionsPanel.js
Implements [TECH-1120](https://dhis2.atlassian.net/browse/TECH-1120)
---
1. Changes the input type to `search` to enable the `X` to clear the field
---
> fix: change input type to search (TECH-1120)

- package.json
- src/components/Dialogs/Conditions/RepeatableEvents.js
- yarn.lock
Implements [TECH-1132](https://dhis2.atlassian.net/browse/TECH-1132)
- Set value to 0 when undefined is passed (e.g. when clicking [backspace] to erase the value
- Set value to 0 when incorrect values are passed (e.g. -1)
> fix: repeated events input validation (TECH-1132)

- src/components/Visualization/Visualization.js
Implements [TECH-1141](https://dhis2.atlassian.net/browse/TECH-1141)
Checks for value type = DATETIME in the header. 
After:
> fix: datetime formatting (TECH-1141)

- src/components/Interpretations/InterpretationModal/InterpretationModal.js
- src/components/Visualization/Visualization.js
- yarn.lock
Implements [TECH-1119](https://dhis2.atlassian.net/browse/TECH-1119)
---
1. disable Prev/Next buttons while data is fetched
2. update @dhis2/ui dep required for this feature
3. fix double scrollbar regression in interpretations modal after the `ui` bump
---
The buttons are disabled as expected.
---
-   [x] even with the buttons disabled it seems the click event on them is registered and queued and executed when the buttons is enabled again. UPDATE: after testing from different people we concluded that technically there isn't anything wrong and it all seems to be related to the timing of the 2 clicks. We'll merge as is and see if people report about this.
---
Before:
After:
> fix: disable pagination while fetching data TECH-1119

- src/components/Visualization/StartScreen.js
Implements [TECH-1148](https://dhis2.atlassian.net/browse/TECH-1148)
> fix: update title for most viewed items (TECH-1148)

- package.json
- src/components/Toolbar/MenuBar/styles/MenuButton.module.css
- yarn.lock
Fixes [TECH-1145](https://dhis2.atlassian.net/browse/TECH-1145)
**Requires https://github.com/dhis2/analytics/pull/1215**
---
1. remove `min-width` on Toolbar buttons
---
The `min-width` was causing inconsistent spacing between buttons in the Toolbar, depending on the length of the button label.
---
---
Before:
After:
> fix: remove min-width on Toolbar buttons TECH-1145

- i18n/en.pot
- src/components/DownloadMenu/DownloadMenu.js
Implements [TECH-1169](https://dhis2.atlassian.net/browse/TECH-1169)
---
1. all labels in Download menu need to be marked from translation
> fix: mark all strings in download menu for translation TECH-1169

- package.json
- src/components/Toolbar/MenuBar/styles/MenuButton.module.css
- yarn.lock
Implements [TECH-1145](https://dhis2.atlassian.net/browse/TECH-1145)
**Requires https://github.com/dhis2/analytics/pull/1220**
---
1. Increase lateral padding for spacing more the buttons
---
Before:
After:
> fix: use larger lateral padding on Toolbar buttons TECH-1145

- src/components/Layout/ChipBase.js
- src/components/Layout/TooltipContent.js
- src/modules/__tests__/conditions.spec.js
- src/modules/conditions.js
Tests for upcoming changes related to [TECH-1150](https://dhis2.atlassian.net/browse/TECH-1150)
---
1. unit tests for conditions
Question: we do not differentiate between case sensitive and non-case sensitive in the tooltip. Intentional, right?
> chore: unit tests for conditions module

- i18n/en.pot
- src/components/Visualization/Visualization.js
- src/modules/error.js
Implements [TECH-1174](https://dhis2.atlassian.net/browse/TECH-1174)
---
1. Catch data access error and provide a custom error message
---
> fix: catch error code for missing data access (TECH-1174)

- src/components/DownloadMenu/useDownloadMenu.js
- src/components/Visualization/useAnalyticsData.js
Implements [DHIS2-13397](https://jira.dhis2.org/browse/DHIS2-13397)
Adds stage to the analytics requests.
> fix: request stage param

- cypress/data/index.js
- cypress/helpers/layout.js
- cypress/integration/conditions/alphanumeric_conditions.cy.js
- cypress/integration/conditions/boolean_conditions.cy.js
- cypress/integration/conditions/date_conditions.cy.js
- cypress/integration/conditions/numeric_conditions.cy.js
- cypress/integration/conditions/orgunit_condition.cy.js
- cypress/integration/conditions/unsupported_types.cy.js
- src/components/Dialogs/Conditions/AlphanumericCondition.js
- New tests for alphanumeric types
- New tests for unsupported types (age, coordinate)
- New tests for the org unit type
> test: alphanumeric conditions + unsupported types + org unit

- docs/line_list.md
Some fixes and suggestions for the doc.
> docs: align a bit better with our docs style

- cypress/integration/layout.cy.js
- src/components/Layout/Layout.js
Tests the little expansion toggle in the layout that makes the layout area grow and shrink.
> test: expansion toggle in the layout

- src/components/Visualization/styles/StartScreen.module.css
Sets landing page title font weight to 500.
> fix: title font weight

- src/components/Dialogs/Conditions/ConditionsManager.js
- src/components/Dialogs/DynamicDimension.js
hides the log output for dimension related info in prod
> chore: hide log for dimensions in prod

- cypress/integration/repeated_events.cy.js
- cypress/integration/translations.cy.js
Adds tests for asserting that translations from i18n display correctly.
> test: translations with i18n

- cypress/integration/conditions/alphanumeric_conditions.cy.js
- cypress/integration/conditions/date_conditions.cy.js
- cypress/integration/conditions/numeric_conditions.cy.js
- cypress/integration/conditions/option_set_condition.cy.js
Unskips tests related to the following backend fixes:
1. [DHIS2-13573](https://dhis2.atlassian.net/browse/DHIS2-13573)
2. [DHIS2-13588](https://dhis2.atlassian.net/browse/DHIS2-13588)
3. [DHIS2-13563](https://dhis2.atlassian.net/browse/DHIS2-13563)
Skips a test related to this newly raised backend bug: 
- [DHIS2-13693](https://jira.dhis2.org/browse/DHIS2-13693)
> test: remove skip to test new backend fixes

- cypress/data/index.js
- cypress/integration/create_enrollment.cy.js
- cypress/integration/create_event.cy.js
- cypress/integration/time_dimensions.cy.js
Adds tests to all time dimensions by verifying their enabled/disabled state, names, chip label and column header label.
> test: time dimensions

- src/components/Visualization/Visualization.js
> fix: avoid cannot update component error

- src/components/Visualization/useAnalyticsData.js
Implements [DHIS2-13787](https://dhis2.atlassian.net/browse/DHIS2-13787)
---
1. conditionally exclude stage from analytics request
> fix: stage param should be removed for enrollments (DHIS2-13787)

- cypress/integration/programDimensions.cy.js
- i18n/en.pot
- src/components/MainSidebar/ProgramDimensionsPanel/ProgramDimensionsPanel.js
- src/components/MainSidebar/ProgramDimensionsPanel/StageSelect.js
Implements [DHIS2-13788](https://dhis2.atlassian.net/browse/DHIS2-13788)
---
1. only display clear button when more than 1 stage
2. reset search term and dimension type when stage is cleared
_program with a single stage_
> fix: program and stage changes (DHIS2-13788)

- cypress/integration/conditions/numericConditions.cy.js
- src/components/Dialogs/Conditions/NumericCondition.js
Implements [DHIS2-13924](https://dhis2.atlassian.net/browse/DHIS2-13924)
---
1. fixes a bug where 0 couldn't be entered as a condition value for integer types
---
> fix: allow integer to use 0 as condition value (DHIS2-13924)

- docs/line_list.md
**Active**, **Completed**, **Scheduled**.
> docs: update event status text

- src/components/Dialogs/Conditions/AlphanumericCondition.js
- src/components/Dialogs/Conditions/BooleanCondition.js
- src/components/Dialogs/Conditions/DateCondition.js
- src/components/Dialogs/Conditions/NumericCondition.js
- src/components/Dialogs/FixedDimension.js
- src/components/Dialogs/PeriodDimension/PeriodDimension.js
- src/components/Visualization/Visualization.js
- src/components/Visualization/useAnalyticsData.js
- src/modules/conditions.js
- src/modules/metadata.js
- src/modules/visualization.js
Implements [DHIS2-13931](https://dhis2.atlassian.net/browse/DHIS2-13931)
---
Adds translations for:
1. event status and program status options in the conditions modal
2. top buttons in the time dimensions modal
3. condition operators in the program dimensions modal
---
_before_
_after_
_before_
_after_
_before_
_after_
> fix: missing translations in LL (DHIS2-13931)

- cypress/integration/timeDimensions.cy.js
- i18n/en.pot
- src/actions/ui.js
- src/components/MainSidebar/DimensionItem/DimensionItemBase.js
- src/modules/__tests__/timeDimensions.spec.js
- src/modules/timeDimensions.js
Implements [DHIS2-13904](https://dhis2.atlassian.net/browse/DHIS2-13904)
---
1. Hide schedule date based on stage setting
---
> fix: scheduled date being hidden by program stage not respected (DHIS2-13904)

- cypress/helpers/interpretations.js
- cypress/helpers/menubar.js
- cypress/integration/download.cy.js
- cypress/integration/interpretations.cy.js
- cypress/integration/legendSet.cy.js
- cypress/integration/new.cy.js
- cypress/integration/period.cy.js
I've scanned all the test files and added EXTENDED_TIMEOUTs to tests where I thought there was potential for timeout failures.
> chore: add additional extended timeouts for cypress tests

- src/components/Toolbar/MenuBar/MenuBar.js
- src/modules/layoutValidation.js
Implements [DHIS2-14087](https://dhis2.atlassian.net/browse/DHIS2-14087)
- Fixes the edge case identified during KFMT where `Rename` and `Translate` did not work
- Fixes more edge case states that were not yet identified, see the table overview in the jira ticket
- Upgrades analytics to [24.3.3](https://github.com/dhis2/analytics/pull/1372).
> fix: props from visualization missing in file menu

- cypress/helpers/dimensions.js
- cypress/integration/fileMenu.cy.js
- src/components/Toolbar/MenuBar/MenuBar.js
Adds more tests for https://dhis2.atlassian.net/browse/DHIS2-14087
> test: more file menu state tests (DHIS2-14087)

- cypress/helpers/period.js
- cypress/integration/conditions/optionSetCondition.cy.js
- cypress/integration/fileMenu.cy.js
Fixes:
- Text option set test
From @jenniferarnesen's PR:
- cy.contains() vulnerability
- Improved way of closing the file menu
> test: fix option set test

- cypress/helpers/transfer.js
- cypress/integration/conditions/optionSetCondition.cy.js
Wait for options to be loaded before filtering or double clicking.
> test: option set transfer fix

- cypress/integration/repeatedEvents.cy.js
- src/actions/visualization.js
Implements [DHIS2-14269](https://dhis2.atlassian.net/browse/DHIS2-14269)
Adds missing metadata for stages when using cross-stage data elements.
> fix: repeatable event repetition cannot be edited after saving as favorite (DHIS2-14269)

- cypress/integration/timeDimensions.cy.js
After the db change we need to use a stage from a different program.
> test: fix scheduled date test by using a different program

- cypress/integration/options.cy.js
Update the display density test to match the `Normal` display density.
> test: update density test

- package.json
- src/components/Visualization/Visualization.js
- yarn.lock
1. update cli-app-scripts
2. update analytics
3. replace `useOnlineStatus` with `useDhis2ConnectionStatus`
---
The gray background in the initial loading spinner is removed (cli-app-scripts).
More fixes to FileMenu -> GetLink (analytics).
The offline detection has changed and need to be aligned in all apps.
> fix: update cli-app-scripts and analytics

- cypress/integration/eventStatus.cy.js
- cypress/integration/options.cy.js
- cypress/integration/table.cy.js
Adds tests for [DHIS2-2367](https://dhis2.atlassian.net/browse/DHIS2-2367)
Also unskips a test that was previously blocked by [DHIS2-14442](https://dhis2.atlassian.net/browse/DHIS2-14442)
[DHIS2-2367]: https://dhis2.atlassian.net/browse/DHIS2-2367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-14442]: https://dhis2.atlassian.net/browse/DHIS2-14442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test: ou hierarchy tests (DHIS2-2367)

- .github/workflows/e2e-prod.yml
switching as ’test.e2e’ is broken/slow, hopefully ’debug’ works better
clone of https://github.com/dhis2/data-visualizer-app/pull/2619
> chore: switch test server to debug

- cypress/fixtures/yourDimensionsLazyLoading.json
- cypress/integration/programDimensions.cy.js
- cypress/integration/yourDimensions.cy.js
- src/components/MainSidebar/DimensionsList/DimensionsList.js
- src/components/MainSidebar/DimensionsList/DimensionsList.module.css
- src/components/MainSidebar/MainSidebar.module.css
- src/components/MainSidebar/ProgramDimensionsPanel/useProgramDataDimensions.js
- src/components/MainSidebar/YourDimensionsPanel/useYourDimensions.js
- src/configureStore.js
Implements [DHIS2-16083](https://dhis2.atlassian.net/browse/DHIS2-16083)
---
1. Fixes lazy loading of the "your dimensions" list
---
Three unrelated issues were preventing this list from lazy loading properly:
1. Due to a CSS issue the scroll-box container was actually the scrolling element instead of the scrollbox itself. This caused three issues:
1. Since the scrollbox was growing to the full list height, the list was "lazy loading" all of its pages in one go, because the end of the list was always visible.
2. Scrolling down to the bottom would not trigger anything to happen.
3. The search input would scroll out of view when scrolling down
2. When computing the next page we were incrementing from a wrong property causing the next page to be `NaN`
3. The `DimensionList` component assumes …
> fix: your- and program-dimensions list lazy loading

- src/actions/visualization.js
- src/components/App.js
- src/components/MainSidebar/ProgramDimensionsPanel/ProgramDataDimensionsList.js
- src/components/MainSidebar/ProgramDimensionsPanel/ProgramDimensionsPanel.js
- src/components/MainSidebar/ProgramDimensionsPanel/useProgramDataDimensions.js
- src/components/Visualization/useAnalyticsData.js
- src/modules/current.js
- src/modules/utils.js
Implements [DHIS2-XXXX](https://dhis2.atlassian.net/browse/DHIS2-XXXX)
**Requires https://github.com/dhis2/analytics/pull/XXX**
---
1. _feature_
---
_text_
---
-   [ ] Cypress tests
-   [ ] Update docs
-   [ ] KFMT
-   [ ] _task_
---
-   [ ] _issue_
---
_supporting text_
> feat: enable tracked entity type analytics fetch

- cypress.config.js
- jest.config.js
not push the test results to report portal when running the test locally
> test: send jest test results only when env is setup

- .github/workflows/dhis2-verify-app.yml
- jest.config.js
add extra attributes (BRANCH_NAME, CI_BUILD_ID and PR_TITLE) to easily identify jest tests runs in report portal
> test: add report portal attributes (BRANCH_NAME, CI_BUILD_ID and PR_TITLE) 

- cypress/data/index.js
- cypress/integration/yourDimensions.cy.js
Adapts the Cypress test suite to the new version of the database
> test: adapt tests to new database

- package.json
- yarn.lock
> fix: paragraph newlines are not rendered in Interpretations and Details description

- .github/workflows/dhis2-verify-app.yml
- README.md
This PR optimises our Cypress test recording triggers and updates the documentation to reflect these changes.
1. **Workflow Trigger Changes:**
- Updated the trigger types to include `labeled` events and removed the `edited` trigger, preventing unnecessary re-runs due to PR description or title edits.
2. **Recording Trigger Logic:**
- Introduced logic to activate recordings via commit messages (`[e2e record]`) or GitHub labels (`e2e record`), providing versatility in how recordings are triggered.
3. **README Update:**
- Added a new section on **Conditional E2E Test Recording** to guide the use of commit messages and labels for triggering recordings.
These updates simplify the process of managing Cypress Cloud credits and enable precise control over when recordings are made, reducing …
> chore: optimize Cypress recordings with conditional triggers

- .github/workflows/dhis2-preview-pr.yml
- .github/workflows/dhis2-verify-commits.yml
- .github/workflows/e2e-dev.yml
- .github/workflows/nightly.yml
- .github/workflows/publish-d2-ci.yml
- .github/workflows/release.yml
- .github/workflows/verify-pr.yml
Implements [DHIS2-18298](https://dhis2.atlassian.net/browse/DHIS2-18298)
---
1. Upgrades all GitHub Actions
2. For actions that could not be upgraded a note explains why
[DHIS2-18298]: https://dhis2.atlassian.net/browse/DHIS2-18298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: update all actions to latest version [DHIS2-18298]

- README.md
This PR just adds some info to the readme.
> chore: update readme reg. deploy previews

- .github/workflows/verify-pr.yml
- cypress.config.js
- jest.config.js
- package.json
- yarn.lock
https://dhis2.atlassian.net/browse/DHIS2-18491
> chore: remove reportportal integration

- cypress/integration/orgUnitDimension.cy.js
- package.json
- src/modules/__tests__/tableValues.spec.js
- yarn.lock
Implements [DHIS2-18066](https://dhis2.atlassian.net/browse/DHIS2-18066)
---
Includes https://github.com/dhis2/analytics/pull/1702
Updates value test according to a new decimal rule in analytics, see https://github.com/dhis2/analytics/commit/3392d783b51dd8715beb09b673e567580005a0a2#diff-d6720939200e71e4dd637c04e10159281afb026fe5f2724cf9cc4e3c6afe2efeR50
Updates ou dialog tests according to new behaviour.
---
-   [ ] Manual testing
[DHIS2-18066]: https://dhis2.atlassian.net/browse/DHIS2-18066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: enable ou tree and levels/groups with user orgunits (DHIS2-18066)

- cypress/support/e2e.js
See https://github.com/dhis2/data-visualizer-app/pull/3381 for info
> chore: restore old session logic and use loginByApi helper

- .github/pull_request_template.md
- cypress/integration/fileMenu.cy.js
- cypress/integration/save.cy.js
1. update the PR template to show a complete list of quality checks
2. update cypress tests to delete all the visualizations they create
---
> chore: update PR template and update cypress tests to delete all created visualizations

- cypress/support/e2e.js
- package.json
- src/__tests__/cypressGetExcludedTags.spec.js
- yarn.lock
Just a quick PR to upgrade the cypress utils and assert the login request
> chore: upgrade cli-utils-cypress and assert login request

- package.json
- yarn.lock
Implements [DHIS2-19973](https://dhis2.atlassian.net/browse/DHIS2-19973)
Add _N/A_ to items that are not applicable.
[DHIS2-19973]: https://dhis2.atlassian.net/browse/DHIS2-19973?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: update cli-app-scripts to open links in same tab
