- src/components/DndContext.js
- src/components/MainSidebar/DimensionsList/DimensionsList.js
- src/components/MainSidebar/MainDimensions.js
- src/components/MainSidebar/ProgramDimensionsPanel/ProgramDimensionsList.js
- src/components/MainSidebar/TimeDimensions.js
- src/components/MainSidebar/YourDimensionsPanel/YourDimensionsPanel.js
Implements [TECH-1024](https://jira.dhis2.org/browse/TECH-1024)
Potentially improves performance: [TECH-990](https://jira.dhis2.org/browse/TECH-990)
---
1. Remove DnD SortableContext from all the dimension panel lists since it isn't needed (those lists are not droppable/sortable)
2. Add preventDefault to the onMouseDown of DimensionLists to prevent scrolling on the list when dragging an item outside of the list. This fix prevents a bunch of scroll events from firing while dragging and so hopefully will improve the dragging performance a little bit.  Note that if you do drag the item upwards to the top of the list, it will still scroll upwards (video below). I'm still looking for a solution to that behaviour.  
---
Bug behaviour:
https://user-images.githubusercontent.com/6113918/156993533-2 …
> fix: prevent scrolling while dragging item from program dimensions panel

- src/components/Visualization/Visualization.js
Implements [TECH-1025](https://jira.dhis2.org/browse/TECH-1025)
---
1. reset page to 1 when sorting
---
When sorting on a column, the page should be reset to 1 instead of keeping whatever page is currently selected.
> fix: reset page to 1 when a sorting is applied (TECH-1025)

- src/components/Layout/TooltipContent.js
Program indicators don't have value type, so when fetching `getOperatorsByValueType` `undefined` is passed in, resulting in no operators being returned.
This fix defaults the switch/case to the numeric operators, which aligns with the program indicators (all program indicators are numeric, as seen here:
https://github.com/dhis2/line-listing-app/blob/7ce2f2295b085ea7ef44d89328f05e3d48a694f3/src/components/Dialogs/Conditions/ConditionsManager.js#L234
> fix: operators for program indicators

- src/components/Visualization/Visualization.js
1. fix id used to open dimension modal for dimensions with repeatable events
---
The key used to open the dimension modal should not contain the repeatable index, only program stage and dimension ids.
> fix: remove stage index from dimension id used for modal

- i18n/en.pot
- src/components/DndContext.js
- src/components/Layout/Chip.js
- src/components/Layout/ChipBase.js
- src/components/Layout/DefaultLayout/DefaultAxis.js
- src/components/Layout/TooltipContent.js
- src/components/Layout/styles/Chip.module.css
- src/modules/conditions.js
- src/reducers/ui.js
Implements [TECH-1009](https://jira.dhis2.org/browse/TECH-1009)
---
1. Add stageName to the chip label in cases where multiple data elements have the same name. This is the same functionality used by ProgramDimensionsList (code is duplicated for now, but will consider refactoring when adding stageName to modal and the visualization columns)
2. Style the chip such that the suffix showing #selected/conditions always shows in full, and the name-stageName part being truncated with overflow ellipsis.
3. move TooltipContent->renderConditions to function getConditions in modules/conditions. This was so that the functionality could be shared with the chip label component (ChipBase)
4. refactor: switch DefaultAxis to use useSelector/useDispatch instead of connect. This resulted in …
> fix: chip label with stage name and correct suffix

- src/components/Toolbar/MenuBar/MenuBar.js
1. Fixed default untitled name.
2. Use `getVisualizationFromCurrent` for generating the save payload
(although currently it does not make a difference since all options are
saveable).
---
The `Save` button was always enabled allowing to save (or rather attempting to save) an empty AO, ie. right after clicking `New`.
This resulted in this error:
After using the `getVisualizationFromCurrent` which initialises `current` as an object with a couple of keys, the Save works but the backend returns a different error because of missing keys. In this case the payload only has the options and the name/description (from the prompt) which of course is not enough for a valid Line list AO.
To avoid this errors it makes sense to disable the `Save` button when `current` is empty.
> fix: disable Save if no current

- src/components/MainSidebar/ProgramDimensionsPanel/ProgramDimensionsFilter.js
Implements [TECH-1015](https://dhis2.atlassian.net/browse/TECH-1015)
Hides "Program attributes" for event programs as they don't have a tracked entity type.
Not making this configurable e.g. through props as this component is already very opinionated and not really a plain presentation component.
> fix: hide attributes for event programs

- .github/pull_request_template.md
- src/components/Visualization/Visualization.js
- src/modules/__tests__/timeDimensions.spec.js
- src/modules/dimensionConstants.js
- src/modules/timeDimensions.js
- src/modules/visualization.js
- src/reducers/ui.js
Implements [TECH-1040](https://dhis2.atlassian.net/browse/TECH-1040)
---
1. rename `lastUpdated` to `lastUpdatedDate`
---
The field has been renamed in the backend, see https://jira.dhis2.org/browse/DHIS2-12856.
The header field name remains `lastupdated`.
---
Example of saved AO with `lastUpdatedDate` dimension, save and load works as it should:
> fix: rename lastUpdated to lastUpdatedDate TECH-1040

- src/actions/current.js
- src/actions/ui.js
- src/components/App.js
- src/components/Toolbar/MenuBar/MenuBar.js
- src/components/Visualization/Visualization.js
- src/components/Visualization/useAnalyticsData.js
- src/reducers/ui.js
Implements [TECH-1033](https://dhis2.atlassian.net/browse/TECH-1033)
1. sortField, sortDirection and page number need to be stored in redux store since multiple components change the values (sorting buttons on table, and the Update button). With this change, the sorting and current data in store are coordinated so that the api request  in useAnalyticsData only triggers once.
You could argue that `page` shouldn't be bundled together with the sortField/sortDirection in the same redux property, but they are connected in many cases, so I went ahead and bundled them. Also, I left pageSize in Visualization component state since only the table causes changes to that value or is dependent on that value.
Sort and then change the column order and then update …
> fix: prevent extra api request and render of vis table when sorting and updating

- package.json
- src/components/Toolbar/MenuBar/MenuBar.js
- yarn.lock
Related to https://github.com/dhis2/analytics/pull/1176
1. Filter only LL AOs
2. Remove the vis type filter in the dialog
---
We only want to list Line list AOs.
---
No vis type filter:
Query filter for LL AOs only:
> fix: remove vis type filter in OpenFileDialog and filter only LL AOs

- src/components/Visualization/Visualization.js
- src/modules/__tests__/timeDimensions.spec.js
- src/modules/dimensionConstants.js
- src/modules/timeDimensions.js
- src/modules/visualization.js
- src/reducers/ui.js
Related to [TECH-1040](https://dhis2.atlassian.net/browse/TECH-1040)
---
1. rename `lastUpdatedDate` back to `lastUpdated`
---
Network request:
> fix: revert rename lastUpdated to lastUpdatedDate TECH-1040

- src/components/Dialogs/PeriodDimension/PeriodDimension.js
- src/components/Dialogs/PeriodDimension/StartEndDate.js
Implements [TECH-1044](https://dhis2.atlassian.net/browse/TECH-1044)
Implements [TECH-1052](https://dhis2.atlassian.net/browse/TECH-1052)
1. When the period selector is opened, the correct tab is now preselected
2. Enables dates to be removed/cleared
> fix: open correct tab, enable date to be removed (TECH-1044, TECH-1052)

- src/components/Visualization/Visualization.js
Implements [TECH-1054](https://dhis2.atlassian.net/browse/TECH-1054)
---
1. make URLs clickable in datatable
---
Row values of `URL` type should be rendered as `<a>` tags to make them clickable and open in a new tab.
---
> fix: make URL values in datatable clickable TECH-1054

- src/components/Visualization/Visualization.js
The issue only occured when navigating backwards from the last page. The "next" button is disabled when on the last page, so the combination of "fetching" and "isLastPage" covers this. All previous pages will have the same number of items as the page size, so using that to set the correct length.
> fix: pass correct page length to pager

- src/components/App.js
- src/modules/current.js
Implements [TECH-1059](https://dhis2.atlassian.net/browse/TECH-1059)
---
1. avoid saving empty object for `programStage` in `current` TECH-1059
2. fix loading of AO when `programStage` is not present
---
`programStage` is not always selected in a AO.
Remove if empty when saving and don't assume it's present with an `id` when loading an AO.
---
_supporting text_
> fix: programStage issues when saving/loading AO

- src/actions/loader.js
- src/actions/metadata.js
- src/actions/ui.js
- src/components/App.js
- src/reducers/metadata.js
Implements [TECH-1049](https://dhis2.atlassian.net/browse/TECH-1049)
1. Add CLEAR_METADATA to tSetInitMetadata and make sure it is called when use clicks New, Open and Delete. This will ensure that the metadata in the store doesn't grow in size and potentially become a performance bottleneck.
> fix: reinitialize metadata when new, opening, and deleting an AO

- src/components/Visualization/Visualization.js
Implements [TECH-1060](https://dhis2.atlassian.net/browse/TECH-1060)
---
1. do not show "Invalid date" for empty dates
---
`moment` is used to format the dates in the DataTable.
When an empty/undefined value is passed, `format` returns the "Invalid date" text.
If the date value is empty/undefined, do not attempt to format it with `moment`.
---
Before:
After:
> fix: do not show Invalid date for empty dates (TECH-1060)

- src/components/DndContext.js
1. PointerSensor is actually the default sensor for dndkit. We modify the sensor so that a 15 pixel movement is needed before drag behaviour triggers. This is so that the chips and dimensions can still be clicked on to open the modal. I had inadvertently used the MouseSensor for this instead of PointerSensor
> fix: use dnd pointer sensor so most devices can use drag and drop

- src/actions/ui.js
- src/actions/visualization.js
- src/api/legendSets.js
- src/components/Dialogs/Conditions/RepeatableEvents.js
- src/components/Dialogs/DynamicDimension.js
- src/components/Dialogs/FixedDimension.js
- src/components/DndContext.js
- src/components/Layout/DefaultLayout/DefaultAxis.js
- src/components/MainSidebar/ProgramDimensionsPanel/useProgramDimensions.js
- src/components/Visualization/useAnalyticsData.js
- src/modules/__tests__/utils.spec.js
- src/modules/current.js
- src/modules/utils.js
- src/reducers/ui.js
Implements [TECH-1066](https://dhis2.atlassian.net/browse/TECH-1066)
---
1. Makes sure repetition is only saved when the value is non-default (TECH-1066)
2. Refactors parse and concat of dimensionId/programStageId to use util functions `formatDimensionId` and
`extractDimensionParts`
3. (BONUS) changes the prop type for `isInLayout` which was throwing console errors
> fix: repetition index issues (TECH-1066)

- i18n/en.pot
- src/components/Layout/TooltipContent.js
Implements [TECH-1071](https://dhis2.atlassian.net/browse/TECH-1071)
---
1. Since ":" is the default separator for strings, indicate a different separator for this particular string which contains a colon.
> fix: use a separator that is not a colon for this string

- src/modules/error.js
Implements [TECH-1068](https://dhis2.atlassian.net/browse/TECH-1068)
1. when entering start/end dates, it is possible to enter a date that is not considered valid by the backend, e.g., 10-10-20222.
In this case, a time dimension has been selected, but it is not valid. The error message has been updated to better reflect this.
> fix: message should handle case where an invalid date has been selected

- src/components/Dialogs/AddToLayoutButton/AddToLayoutButton.js
- src/components/Dialogs/DimensionModal.js
Implements [TECH-1084](https://dhis2.atlassian.net/browse/TECH-1084)
---
1. Prevents the _Add to layout_ button from triggering an update (and is thus now gray instead of blue)
---
> fix: prevent add to layout button from triggering an update (TECH-1084)

- src/components/Dialogs/PeriodDimension/PeriodDimension.js
- src/components/Dialogs/PeriodDimension/StartEndDate.js
Implements [TECH-1061](https://dhis2.atlassian.net/browse/TECH-1061)
Prevents time dimensions from being wiped when the modal is reopened. Incomplete start/end dates are still removed as they should.
Needs to be tested thoroughly.
> fix: prevent time dims from being wiped when reopening modal (TECH-1061)

- src/configureStore.js
- src/modules/visualization.js
Implements [TECH-1092](https://dhis2.atlassian.net/browse/TECH-1092)
---
1. remove legacy flag when saving a copy
---
When saving a copy of an AO created with the Event Reports app, remove the legacy flag, which would have a `true` value.
This copy won't work in Event Reports app anyway.
This also unlocks the Save button on the copied (and converted to new format) AO in LL app.
---
Snipped of the payload, where `legacy` is not present:
> fix: remove legacy flag when saving a copy TECH-1092

- src/components/Dialogs/Conditions/OptionSetCondition.js
Implements [TECH-1082](https://dhis2.atlassian.net/browse/TECH-1082)
---
1. use `code` instead of `value` when evaluating paging
---
There's a special edge case for the Transfer component (described in a long comment in the code), which was previously evaluating the `value` prop, which is incorrect for fetching options (copy-paste error from DV), so it has now been switched to evaluate `code` instead.
The "Select all" button now works properly again.
---
_Clicking "Select all" no longer triggers an infinite loop of loading new results_
> fix: option set to use code instead of value for paging (TECH-1082)

- i18n/en.pot
- src/components/Visualization/Visualization.js
- src/modules/error.js
Implements [TECH-1097](https://dhis2.atlassian.net/browse/TECH-1097)
---
1. Catches E7132 and outputs a user-friendly error message instead
---
> fix: catch error code for indicator error and display a custom error msg (TECH-1097)

- src/components/MainSidebar/DimensionItem/DimensionItemBase.module.css
Adds margin that went missing after https://github.com/dhis2/line-listing-app/pull/91
_before_
_after_
> fix: add missing margin to dimension menu

- src/components/Interpretations/common/Message/MessageIconButton.js
Fixes [TECH-1085](https://dhis2.atlassian.net/browse/TECH-1085)
---
1. align vertically all action buttons
---
The `renderProps` approach is used to be able to add custom styles to the wrapper `span` elements.
---
Before:
After:
> fix: fix vertical alignment of interpretation action buttons TECH-1085

- src/actions/ui.js
- src/reducers/settings.js
- src/reducers/ui.js
Implements [TECH-1091](https://dhis2.atlassian.net/browse/TECH-1091)
---
1. use default from system settings for DGS
---
In the Options dialog, use the default set in system settings for the digit group separator.
---
https://user-images.githubusercontent.com/150978/163134973-e62f70c8-e528-4926-bf1f-6e735c395942.mov
> fix: use system settings for DGS option TECH-1091

- src/components/Dialogs/Conditions/DateCondition.js
- src/modules/conditions.js
1. adds `max` to `datetime` and `date` condition inputs
2. formats the tooltip for `datetime` and `time`
---
_set max to `date`_
_set max to `datetime`_
---
_`datetime` tooltip before_
_`datetime` tooltip after_
---
_`time` tooltip before_
_`time` tooltip after_
> fix: format date and datetime

- src/components/Interpretations/common/Message/MessageIconButton.js
Implements [TECH-1086](https://dhis2.atlassian.net/browse/TECH-1086)
---
1. use a different color when hovering the interpretation's action button
---
On hover a tooltip is shown but we also want to make it more visible that those are buttons.
---
> fix: use different color on hover for action buttons TECH-1086

- src/components/MainSidebar/ProgramDimensionsPanel/ProgramDimensionsList.js
- src/components/MainSidebar/ProgramDimensionsPanel/ProgramDimensionsPanel.js
- src/components/MainSidebar/ProgramDimensionsPanel/useProgramDimensions.js
Implements [TECH-1089](https://dhis2.atlassian.net/browse/TECH-1089)
---
1. In order to preserve the fetched dimensions, ProgramDimensionsList cannot be un-mounted when collapsing the Program Dimensions panel, so that the useProgramDimensions hook retains its local state.
2. Very small refactor: move the `userSettings` hook to useProgramDimensions, where it is actually needed.
---
-   When expanding the panel, the list will scroll up to the top. Not sure if this is an annoyance or a bonus.
-  There might be a teeny-tiny bit of sluggishness when expanding the panel, if the dimension list is very long (due to lots of previous scrolling down)
---
https://user-images.githubusercontent.com/6113918/165491134-265bec51-b375-4ffb-bc32-420edb4f1feb.mov
> fix: preserve fetched dimensions when collapsing Program Dimensions panel

- src/components/MainSidebar/ProgramDimensionsPanel/ProgramDimensionsList.js
- src/components/MainSidebar/ProgramDimensionsPanel/ProgramDimensionsPanel.js
Implements [TECH-1137](https://dhis2.atlassian.net/browse/TECH-1137)
---
1. Use the small version of the spinner in the program dimensions list
2. Removed the `LoadingMask` usage since a `loading` prop is passed to the
child component and it controls a spinner already.
---
See screenshots
---
Before:
After:
> fix: use small circular loader in program dim list TECH-1137

- src/components/App.js
Implements [TECH-1139](https://dhis2.atlassian.net/browse/TECH-1139)
---
1. Only set `fetchError` when actually loading
---
Previously, after loading a 404 AO (e.g. `#/nothing`) the `fetchError` would reappear later when the user made changes to the layout. This was because `fetchError` was kept in the local state of `App.js`. There's no apparent reason for keeping this local state, as the error handling for fetch errors proceed with saving the error in the redux store, so no need to keep it locally as well.
This PR removes `fetchError` from the local state to make sure the "zombie error" doesn't reemerge at an unexpected time.
> fix: prevent fetchError from reemerging when not loading (TECH-1139)

- src/components/MainSidebar/DimensionItem/DimensionItemBase.module.css
Implements [TECH-1133](https://dhis2.atlassian.net/browse/TECH-1133)
Before:
After:
Before (with stage):
After, (with stage ):
> fix: add overflow-wrap: anywhere for wrapping of text in dimension item

- src/modules/conditions.js
Phone number use alpha numeric operators but was accidentally listed to be using numeric operators
> fix: use correct operator type for phone number (TECH-1147)

- src/components/DimensionMenu/DimensionMenu.js
- src/components/MainSidebar/DimensionItem/DimensionItemBase.js
- src/components/MainSidebar/TimeDimensions.module.css
Implements [TECH-1135](https://dhis2.atlassian.net/browse/TECH-1135)
---
1. Fixes time dimensions so they span the full width
2. Make the right side of the dimension items clickable
---
Part 1: see screenshot below.
Part 2: there's a special way to handle the onClick callbacks, as all three implementers of the `toggleMenu` does it differently. `Layer` has `e` as the second prop, hence the `_` fix (thanks @edoardo. That one plus the "open" (from the dot-dot-dot menu) as `e` and needs the `stopPropagation`, while the last case (when closing because a menu item has been clicked) doesn't have an event (`e`) at all.
---
_time dimensions span the full width now_
> fix: dimension item fixes (TECH-1135)

- src/components/TitleBar/TitleBar.js
Implements [TECH-1170](https://dhis2.atlassian.net/browse/TECH-1170)
---
1. show translated title
---
`displayName` should be used to show the translated title based on the current user's locale when available.
---
Before:
After:
> fix: show translated title TECH-1170

- src/components/Interpretations/common/Message/Message.js
Implements [TECH-1175](https://dhis2.atlassian.net/browse/TECH-1175)
---
1. Uses locale format for interpretations instead of hardcoded static format
---
_english before_
_english after_
_mongolian before_
_mongolian after_
_burmese before_
_burmese after_
> fix: interpretations use locale format (TECH-1175)

- package.json
- yarn.lock
Implements [LIBS-317](https://dhis2.atlassian.net/browse/LIBS-317)
**Requires https://github.com/dhis2/d2-ui/pull/730**
---
1. enable support for Markdown links (via `d2-ui-rich-text` dependency) 
---
See screenshots
---
Before:
After:
> fix: update d2-ui-rich-text dependency LIBS-317

- src/components/Dialogs/Conditions/DateCondition.js
- src/modules/conditions.js
Implements [TECH-1183](https://dhis2.atlassian.net/browse/TECH-1183)
---
1. Prevent `replaceAll` from crashing when `value` is `undefined`
> fix: prevent replaceAll from crashing due to undefined value (TECH-1183)

- package.json
1. start the proxy on the same port specified in `cypress.env.json`
---
Most likely people copy-paste the configuration for the `cypress.env.json` from the `README` file, where we use `8081` as the proxy port for the backend.
Starting the proxy on the same port avoids the proxy to use the default `8080` is no proxy on that port is already running.
> fix: start the proxy on the same port as in cypress.env.json

- src/components/VisualizationOptions/VisualizationOptionsManager.js
- src/modules/options/config.js
- src/modules/options/lineListConfig.js
Implements [DHIS2-75](https://jira.dhis2.org/browse/DHIS2-75)
---
1. Prevent the legend tab from being displayed on servers < 2.38.1
---
This is based on the theory (currently untested) that only the saving part for legend sets needs to be feature toggled. As legend sets themselves are optional, so if the user can't save an AO with one then legend sets will never be present when loading (since the `/eventVisualizations` endpoint handles non-existing params gracefully).
> fix: use feature toggling for the legend tab in options (DHIS2-75)

- src/components/App.js
- src/components/Visualization/Visualization.js
1. replace `acSetLoadError` with a `onError` callback
2. replace `acSetUiDimensionModal` with a `onColumnHeaderClick` callback
---
The plugin cannot rely on the app's Redux store, as it should be standalone so it can be reused in different places, like dashboard app.
The error handling is now using a callback, similarly to how it's done already in the DV plugin.
If there is an error in the plugin (most likely an error returned from the analytics endpoint) and if the `onError` callback prop is provided, the plugin simply calls the callback.
The error is now handled in the `App` component.
In the LL app we want the column header to open the correct dimension modal when clicked, this is now also achieved via a callback, so the app is responsible of setting the modal id in its Redux store.
> fix: untie Plugin component from the app's Redux store

- cypress/data/index.js
- cypress/helpers/dimensions.js
- cypress/integration/conditions/boolean_conditions.cy.js
- cypress/integration/conditions/numeric_conditions.cy.js
- cypress/integration/contextMenu.cy.js
- cypress/integration/create_enrollment.cy.js
- cypress/integration/create_event.cy.js
- cypress/integration/new.cy.js
- cypress/integration/options.cy.js
- cypress/integration/userDimensions.cy.js
Using lists for test data started as a good idea but turned out to be very confusing to use, e.g. `SOME_LIST[0]` gives no contextual meaning to which object it's referring to.
The lists are now split into individual objects which are easier to pick and understand.
> test: refactor lists to individual objects

- src/components/MainSidebar/DimensionsList/DimensionsList.js
- src/components/Toolbar/MenuBar/MenuBar.js
1. avoid encoding when interpolating certain variables in i18n.t.
> fix: avoid encoding when interpolating certain variables in i18n.t

- src/components/Visualization/Visualization.js
Implements [DHIS2-13493](https://jira.dhis2.org/browse/DHIS2-13493)
---
1. avoid crash when pager object in analytics response is malformed
---
The analytics API in some circumstances returns a malformed `pager` object in the response.
The request made from the analytics apps pass `pageSize` in the query string, this same value should be always returned back from the API.
Also, if  nothing is returned in `rows`, `isLastPage` should be `true`.
The crash is caused by the `Rows per page` select in the `Pagination` component, which does not have `0` listed in its options.
To avoid the crash, instead of relying solely on the API response, we now use a value present among the `Rows per page` options whenever the `pageSize` from the API response is `0`.
---
Malformed response (notice …
> fix: avoid crash when pager object in response is malformed DHIS2-13493

- cypress/integration/repeated_events.cy.js
- src/components/Dialogs/Conditions/ConditionsManager.js
- src/components/Dialogs/Conditions/RepeatableEvents.js
Adds tests for the repeated events tab in the conditions modal, which is only enabled for repeatable stages in enrollment programs.
> test: repeated events

- src/components/Dialogs/Conditions/ConditionsManager.js
- src/components/Dialogs/Conditions/NumericCondition.js
Implements [DHIS2-13326](https://jira.dhis2.org/browse/DHIS2-13326)
---
1. Restrict decimals from being used with integer conditions
---
This prevents decimals from being used with integer types (Integer, Positive Integer, Negative Integer, Positive or Zero Integer) in the conditions modal. Similar to how the repeatable events modal restricts decimals as well, as seen here: https://github.com/dhis2/line-listing-app/blob/014bdbff42b9d9704c3c48b71a476c62447f54ce/src/components/Dialogs/Conditions/RepeatableEvents.js#L49
> fix: condition for Integer data element accepts decimal, causing 409 (DHIS2-13326)

- src/components/Visualization/Visualization.js
- src/components/Visualization/styles/Visualization.module.css
Adds a fix for empty rows being shorter than rows with actual content
_before_
_after_
> fix: empty row height

- cypress/data/index.js
- cypress/helpers/period.js
- cypress/integration/legendSet.cy.js
- package.json
- src/components/DetailsPanel/DetailsPanel.js
- yarn.lock
**Requires https://github.com/dhis2/analytics/pull/1335**
- Being able to apply legends to negative values
- Test that multiple legend sets show up properly in the legend key
---
> test: add tests for negative legend sets

- src/components/Layout/styles/Chip.module.css
Implements [DHIS2-13785](https://dhis2.atlassian.net/browse/DHIS2-13785)
---
1. add hover color to empty chip
---
_before: no hover_
_before: hover_
_after: no hover_
_after: hover_
> fix: incorrect hover color for dimensions in filter (DHIS2-13785)

- src/api/options.js
Implements [DHIS2-13772](https://dhis2.atlassian.net/browse/DHIS2-13772)
---
1. Add missing translations for option set options
---
Switches the option set options from `name` to `displayName` to make sure translated names are returned.
---
> fix: translations do not work in conditions dialog (DHIS2-13772)

- src/components/VisualizationOptions/Options/Legend.js
- src/modules/current.js
Fixes https://dhis2.atlassian.net/browse/DHIS2-13793
- Only merge current state with the new state for saved visualizations.
- Always pass a program stage object. If no id, the id prop is undefined.
- When legend is toggled off we now set the legend strategy to undefined.
> fix: stage is remembered internally after program is cleared

- cypress/integration/createEvent.cy.js
- cypress/integration/layoutValidation.cy.js
- cypress/integration/table.cy.js
- i18n/en.pot
- src/api/options.js
- src/components/Visualization/StartScreen.js
- src/modules/error.js
- src/modules/layoutValidation.js
Implements [DHIS2-13786](https://dhis2.atlassian.net/browse/DHIS2-13786)
---
1. adds a custom error when no stage is selected (when using type: event)
---
---
_error when no stage is selected_
_selecting stage clears the error_
_enrollment is unaffected_
> fix: show error message when no stage is selected for events and tracker programs (DHIS2-13786)

- src/modules/visualization.js
Makes sure we never pass empty program stage object when saving.
> fix: do not pass empty stage when saving

- cypress/integration/eventStatus.cy.js
- cypress/integration/repeatedEvents.cy.js
- cypress/integration/timeDimensions.cy.js
- i18n/en.pot
- src/components/Dialogs/FixedDimension.js
- src/modules/visualization.js
Implements [DHIS2-13881](https://dhis2.atlassian.net/browse/DHIS2-13881)
---
1. Add support for event status 'Scheduled' for `>=2.39`
2. Changes some test data as there's now an additional event in the db that needs to be taken into account
---
---
-   [x] this is only supported in 2.39 but "SCHEDULE" items still show up in 2.38?
---
_conditions modal_
_visualization_
> feat: add "Scheduled" event status  (DHIS2-13881)

- src/components/DownloadMenu/useDownloadMenu.js
Implements [DHIS2-14082](https://dhis2.atlassian.net/browse/DHIS2-14082)
Makes sure `programStage` is passed when defined to plain data source download.
> fix: pass stage for plain data source download (DHIS2-14082)

- cypress/integration/interpretations.cy.js
1. improve interpretations tests to avoid repeated failures
---
Because the old implementation used an existing AO, any time there is a problem on a test run (network, timeouts, etc...) and the tests don't complete, the AO is left in a "dirty" state until the DB is reset or the interpretations are manually removed from the AO.
Instead, before each test run of the interpretations tests, a new AO is created, used and deleted once the tests are completed.
> test: improve interpretations tests

- package.json
- src/components/App.js
- yarn.lock
Implements [DHIS2-14145](https://dhis2.atlassian.net/browse/DHIS2-14145)
**Requires https://github.com/dhis2/analytics/pull/1379**
---
1. fix the error on translations save
2. avoid unnecessary App re-rendering
---
Because the `renderId` is in the App state, every time it's updated the App re-renders.
If the right side panel is closed, there is no need to update the `renderId`.
This avoids an unnecessary re-render of the App component on actions in the FileMenu.
---
The canceled request to `i18n`after saving the translations is gone:
> fix: error when saving translations

- .github/workflows/e2e-tests.yml
1. solve broken video recording on dev tests
---
Electron browser seem to have issues with recording videos of test failures.
Chrome on the other hand works fine.
Always use Chrome for running tests in both production and dev test groups.
> chore: always use headless Chrome for proper video support

- .github/workflows/e2e-tests.yml
- .github/workflows/nightly.yml
1. use Chrome when running Cypress tests for proper video support
---
Electron video recording has problems.
Use Chrome instead for all test runs.
Adjusted the workflow config to remove warnings:
1. Bumped versions of the actions used in the workflow:
- actions/checkout -> v3
- actions/setup-node -> v3
- cypress-io/github-action -> v5
2. Bumped version of node to **18.x**.
3. Removed `headless` and `video` parameter that are not part of the Cypress Github action config.
4. Single quotes around the URL for `wait-on` added everywhere for consistency and to follow the examples in the action documentation.
> chore: force chrome browser for Cypress nightly tests

- cypress/integration/conditions/optionSetCondition.cy.js
- src/modules/__tests__/tableValues.spec.js
- src/modules/tableValues.js
Implements [DHIS2-14172](https://dhis2.atlassian.net/browse/DHIS2-14172)
---
1. Stop applying DGS to optionSet options
---
Values that are actually options from an optionSet shouldn't have digit group separators applied to them, as those values doesn't count as being numeric. This fix prevents any value with an `optionSet` prop from getting formatted with DGS.
---
-   [ ] Cypress tests
---
_before_
_after_
> fix: digit group separator applied to valueType TEXT data elements (DHIS2-14172)

- src/components/MainSidebar/ProgramDimensionsPanel/ProgramDimensionsFilter.js
- src/components/MainSidebar/ProgramDimensionsPanel/ProgramDimensionsPanel.js
- src/components/MainSidebar/ProgramDimensionsPanel/ProgramSelect.js
- src/components/MainSidebar/ProgramDimensionsPanel/StageFilter.js
- src/components/MainSidebar/ProgramDimensionsPanel/StageSelect.js
Implements [DHIS2-14288](https://dhis2.atlassian.net/browse/DHIS2-14288)
---
1. split stage selection by input type to `StageSelect` and `StageFilter`
---
There are two distinct cases for selecting a stage
1. For _input type: Event_ stage is selected together with selecting a program, which affects the whole AO
2. For _input type: Enrollment_ stage can be used as a filter when browsing data elements, which only affects the list of dimensions (comparable to searching using the text field)
The `StageSelect` component was previously used for both of these use cases, which created a bit of a mess both in the code and in the ux. There has previously been a need to stop the "false" stage (_case 2_ above) from being passed to the backend etc, which patched up some of the issues with …
> fix: filtering by stage resets the search and type filters (DHIS2-14288)

- cypress/integration/repeatedEvents.cy.js
- src/actions/ui.js
- src/reducers/ui.js
Implements [DHIS2-14219](https://dhis2.atlassian.net/browse/DHIS2-14219)
Clears the ui.repetition config when switching input. I did not want to clear it as part of clearing the program in case that becomes an issue when we support cross-program selection.
> fix: clear repetition when changing input type (DHIS2-14219)

- .github/workflows/nightly.yml
The link is to the page showing all cypress test runs on the dev branch.
> chore: add link to cypress test runs on dev branch to slack message

- cypress/helpers/common.js
- cypress/helpers/route.js
- cypress/helpers/startScreen.js
- cypress/integration/conditions/alphanumericConditions.cy.js
- cypress/integration/conditions/booleanConditions.cy.js
- cypress/integration/conditions/dateConditions.cy.js
- cypress/integration/conditions/numericConditions.cy.js
- cypress/integration/conditions/optionSetCondition.cy.js
- cypress/integration/conditions/orgunitCondition.cy.js
- cypress/integration/conditions/unsupportedTypes.cy.js
- cypress/integration/createEnrollment.cy.js
- cypress/integration/createEvent.cy.js
- cypress/integration/download.cy.js
- cypress/integration/eventStatus.cy.js
- cypress/integration/fileMenu.cy.js
- cypress/integration/interpretations.cy.js
- cypress/integration/layout.cy.js
- cypress/integration/layoutValidation.cy.js
- cypress/integration/legendSet.cy.js
- cypress/integration/new.cy.js
- cypress/integration/options.cy.js
- cypress/integration/programDimensions.cy.js
- cypress/integration/repeatedEvents.cy.js
- cypress/integration/smoke.cy.js
- cypress/integration/table.cy.js
- cypress/integration/timeDimensions.cy.js
- cypress/integration/translations.cy.js
- cypress/integration/userDimensions.cy.js
- cypress/integration/yourDimensions.cy.js
1. Log the server url in the beginning of each test
---
When debugging tests it's sometimes useful to know which server and instance that is being used. This is written in the cypress log, but the important part of the url is cut off due to its length (e.g. `https://test.e2e.dhis2.org/analytics-dev` displays as `https://test.e2e.dhis2...`).
All calls to `cy.visit` are now consolidated into `goToStartPage` and `goToAO(id)`, which in turn use `cy.log` to print the full url (see screenshot below of it in action).
---
> test: log server url

- cypress/data/index.js
- cypress/integration/conditions/numericConditions.cy.js
- cypress/integration/conditions/optionSetCondition.cy.js
- cypress/integration/layout.cy.js
- cypress/integration/options.cy.js
- cypress/integration/table.cy.js
- cypress/integration/value.cy.js
- src/components/Visualization/Visualization.js
- src/components/Visualization/styles/Visualization.module.css
Implements [DHIS2-13899](https://dhis2.atlassian.net/browse/DHIS2-13899)
- Adds `white-space: nowrap` to cells according to ticket description.
- Adds a few test dims.
- Renames a few test dims to match value type name.
- Makes a very small change to display density (right padding) due to the nowrap css, very rarly visible to the user (ref https://dhis2.atlassian.net/browse/DHIS2-14303)
Before:
After:
> fix: numbers with dgs space wrap on multiple lines (DHIS2-13899)

- cypress/helpers/fileMenu.js
- cypress/integration/fileMenu.cy.js
- cypress/integration/interpretations.cy.js
- cypress/integration/legendSet.cy.js
- cypress/integration/save.cy.js
- package.json
- src/components/Toolbar/MenuBar/MenuBar.js
- yarn.lock
Implements [DHIS2-13835](https://dhis2.atlassian.net/browse/DHIS2-13835)
---
1. Prevents saving without a name from crashing
---
Saving an AO without a name (i.e. empty input field) was causing the app to crash and prevented the AO from being saved. The app is supposed to fill in a name automatically, starting with "Untitled Line list visualization" + today's date.
`visTypeDisplayNames` is an object but was used as a function, which caused saving without a name to crash. Switching to the actual function `getDisplayNameByVisType` solves this.
To test this, the `saveVisualization` and `deleteVisualization` helper functions were added, which also gave cause for refactoring the other tests that were saving and/or deleting as well.
One thing to note about the tests, when an AO is saved without …
> fix: saving on an empty name causes a crash (DHIS2-13835)

- cypress/data/index.js
- cypress/integration/conditions/alphanumericConditions.cy.js
- cypress/integration/conditions/dateConditions.cy.js
- cypress/integration/conditions/numericConditions.cy.js
- cypress/integration/download.cy.js
- cypress/integration/eventStatus.cy.js
- cypress/integration/layoutValidation.cy.js
- cypress/integration/legendSet.cy.js
- cypress/integration/options.cy.js
- cypress/integration/repeatedEvents.cy.js
- cypress/integration/table.cy.js
- cypress/integration/timeDimensions.cy.js
- cypress/integration/value.cy.js
1. Removes all hardcoded references to 2021 and 2022 (replaced by "previous year" and "current year")
2. Removes all references to "Last 12 months" (as this will change over the course of the year)
3. Updates `AGE`, `DATE` and `DATETIME` values from `202x` to `199x` (clear distinction between these data values and actual periods that are bumped each new year)
5. A new `scheduled` event was added to the database for testing
a. Fixed the test for scheduled events, but it's now skipped due to a backend bug, [DHIS2-14442](https://dhis2.atlassian.net/browse/DHIS2-14442)
b.  Test were updated in various places to account for the new event
[DHIS2-14442]: https://dhis2.atlassian.net/browse/DHIS2-14442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test: updates for new year

- .github/workflows/nightly.yml
- cypress/integration/createEnrollment.cy.js
- cypress/integration/createEvent.cy.js
- cypress/integration/programDimensions.cy.js
- cypress/integration/timeDimensions.cy.js
1. Reenables the program dimensions tests
---
The tests in `programDimensions` were disabled due to an overlooked `.only` modifier that should've been removed before merging. As the database used for Cypress tests has changed since then, the program used in the tests didn't work. It turns out the SL database has a program called `WHO RMNCH Tracker` that aligns well with the program previously used (’HIV Case Surveillance’ in the ’analytics_dev’ database).
> test: reenable the program dimensions tests

- cypress/integration/createEnrollment.cy.js
- src/components/DownloadMenu/useDownloadMenu.js
- src/components/MainSidebar/ProgramDimensionsPanel/ProgramDimensionsPanel.js
Implements [DHIS2-14396](https://dhis2.atlassian.net/browse/DHIS2-14396)
---
1. do not set program stage id for enrollments
2. remove the stage from the download request for enrollments
---
Programs with only one stage get the stage automatically selected.
This only make sense when input type is event.
For enrollments we don't pass the stage to the analytics request, this fix avoids that the stage id is stored in the Redux store.
Cypress tests have been adjusted to not look for the program in the disabled time dimension labels.
These dimensions cannot be used with Enrollment input type, so the labels does not make any difference.
It was actually wrong that those dimensions got the program in the label, as for Enrollment multiple programs can be used.
---
Before, program stage id was set …
> fix: do not pre-set program stage for enrollment DHIS2-14396

- .github/workflows/nightly.yml
- src/components/Visualization/Visualization.js
Implements [DHIS2-13950](https://dhis2.atlassian.net/browse/DHIS2-13950)
Resets the page to 1 for new visualizations. Stores the previous visualization in a ref and compares against the prop.
Example: we're on page 5 of a line list. If we listen to `visualization` and do `setPage` when changes, then the data hook first requests data for the new visualization with page 5, which we don't need and want to avoid. When local state for `page` is updated the data hook fires again, this time with page 1.
With this PR the first request is correct and the data engine cancels the second request because it's identical to the first one.
[DHIS2-13950]: https://dhis2.atlassian.net/browse/DHIS2-13950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: reset page on update (DHIS2-13950)

- cypress/helpers/table.js
- cypress/integration/createEnrollment.cy.js
- cypress/integration/table.cy.js
- i18n/en.pot
- src/components/Visualization/Visualization.js
Implements [DHIS2-13948](https://dhis2.atlassian.net/browse/DHIS2-13948)
---
1. reset sorting in component and remove it from analytics request
---
When a column is sorted, the sort field and direction is stored in the component's local state.
If the dimension corresponding to the column is then removed from the layout or moved to filters, the sorting needs to be reset.
---
Before: the `asc` parameter is still passed when the dimension is moved to filters:
After: the `asc` parameter is not passed:
Before: the `asc` parameter is passed even when the corresponding dimension is removed from columns:
After: the `asc` parameter is not passed:
[DHIS2-13948]: https://dhis2.atlassian.net/browse/DHIS2-13948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
> fix: reset sorting when removing dimension from columns DHIS2-13948

- src/components/Visualization/Visualization.js
- src/components/Visualization/useAnalyticsData.js
- src/modules/visualization.js
Implements a part of [DHIS2-2367](https://dhis2.atlassian.net/browse/DHIS2-2367)
We're already mapping dimensions <-> headers, e.g. the `ou` dimension is using the `ouname` header by default. With this PR, the `ou` dimension will use the `ounamehierarchy` header instead when the `showHierarchy` option is enabled. Had to change this in two places. Made a function for it in the module to keep the knowledge about dimension-to-header mapping in one place.
Sorting on this column worked out of the box.
The base for this PR should probably be `feat/DHIS2-2367-ou-hierarchy` / https://github.com/dhis2/line-listing-app/pull/266.
No cypress tests added as there's no way to turn on the hierarchy in this PR.
[DHIS2-2367]: https://dhis2.atlassian.net/browse/DHIS2-2367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmN …
> feat: show ou hierarchy in line lists (DHIS2-2367)

- cypress/integration/conditions/optionSetCondition.cy.js
- cypress/integration/legendSet.cy.js
- cypress/integration/table.cy.js
Requests made by Cypress Dashboard return a different result than requests made by the same test locally and by manual testing both locally and on an instance. The suspicion is that the backend is returning an inconsistent response, e.g. sometimes `['', '11', '12']` and `['12', '11', '']` other times. To prove this theory an assert for the url has been added just before the flaky test. If that url assertion passes but the subsequent test step fails, then it's indeed the backend that is being inconsistent.
e.g. local Cypress / local manual test / instance manual test VS Cypress dashboard test.
There was an issue with 2.39 specifically where option set option `name`s (e.g. `One`) were returned as their `code` (e.g. `1`). This seems to have been fixed on the backend for 2.39 now so the …
> test: fix flaky and outdated tests

- cypress/integration/legendSet.cy.js
As an extension to https://github.com/dhis2/line-listing-app/pull/333, the backend result is now sorted before being evaluated, to make sure the order is always consistent.
> test: sort backend result before evaluating

- cypress/helpers/dimensions.js
- cypress/integration/programDimensions.cy.js
Recently the nightly test run has failed due to the program dimensions list being slow and not rendering within the default 4s timeout. This extends the timeout in all places where program-dimensions-list is used to avoid flakey tests.
> test: add EXTENDED_TIMEOUT to all references of program-dimensions-list

- src/components/Visualization/Visualization.js
- src/components/Visualization/useAnalyticsData.js
- src/components/VisualizationOptions/Options/ShowHierarchy.js
- src/modules/getRequestOptions.js
- src/modules/options.js
- src/modules/options/lineListConfig.js
Implements [DHIS2-2367](https://dhis2.atlassian.net/browse/DHIS2-2367)
Supersedes https://github.com/dhis2/line-listing-app/pull/266
Adds an option for "Display organisation unit hierarchy".
Uses the new `ounamehierarchy` column, ref https://github.com/dhis2/line-listing-app/pull/328.
[DHIS2-2367]: https://dhis2.atlassian.net/browse/DHIS2-2367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add ou hierarchy to options (DHIS2-2367)

- package.json
- src/PluginWrapper.js
- src/modules/getPWAInstallationStatus.js
- yarn.lock
Pretty much a copy of https://github.com/dhis2/data-visualizer-app/pull/2273
Implements [DHIS2-15097](https://jira.dhis2.org/browse/DHIS2-15097)
Will be paired with a dashboard PR: https://github.com/dhis2/dashboard-app/pull/2285
To help test the "installation" handling locally more easily, you can add these lines to `node_modules/@dhis2/pwa/build/es/service-worker/service-worker.js`, at the bottom of `setUpServiceWorker()`, before running `yarn start`:
```js
// Prolong installation event
self.addEventListener('install', (event) => {
console.log('installing')
event.waitUntil(new Promise((res) => {
setTimeout(() => res(), 10000)
}))
})
```
---
1. Sends PWA installation status to the parent app to share when it is cached and ready to be served locally
[DHIS2-15097]: …
> feat(plugin): send installation status

- src/modules/options/lineListConfig.js
Adds a fix to [DHIS2-2367](https://dhis2.atlassian.net/browse/DHIS2-2367)
Adds a 2.40 toggle on the `Show hierarchy` option so that it won't show up in 2.38 and 2.39.
[DHIS2-2367]: https://dhis2.atlassian.net/browse/DHIS2-2367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: add 2.40 toggle to show hierarchy option (DHIS2-2367)

- i18n/es.po
- src/components/MainSidebar/SelectedDimensionsContext.js
When loading a saved line list with multistage data elements we don't have metadata on the "stageId.elementId" format in the loaded visualization object. This causes a crash in the `SelectedDimensionsContext.js` file.
This is a hotfix and simply avoids the destructuring of a non existing object.
The proper fix would be to construct the correct metadata and add it to the metadata store based on the saved line list. With this fix we are not able to restore the dimensions in the ui if the analytics request fails.
> fix: avoid crash when missing metadata for stage-element ids (DHIS2-15423)

- cypress/helpers/common.js
- cypress/helpers/fileMenu.js
- cypress/helpers/table.js
- cypress/integration/fileMenu.cy.js
- cypress/integration/repeatedEvents.cy.js
- cypress/integration/smoke.cy.js
- cypress/support/index.js
- src/components/TitleBar/TitleBar.js
Implements [DHIS2-15063](https://dhis2.atlassian.net/browse/DHIS2-15063)
---
Renames `visualization-title` to `titlebar` for consistency with other apps
Also, prevents ResizeObserver from failing the tests by utilising the check used in Dashboard - [dashboard-app/blob/dev/cypress/support/index.js#L12](https://github.com/dhis2/dashboard-app/blob/dev/cypress/support/index.js#L12)
[DHIS2-15063]: https://dhis2.atlassian.net/browse/DHIS2-15063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test: rename visualization-title to titlebar (DHIS2-15063)

- .github/workflows/nightly.yml
- cypress/integration/value.cy.js
The bot message with the link to the failure was wrong since switching from dev to master.
Also, extended timeout added to hopefully prevent this test from timing out in the future.
> chore: update nightly failure link in bot message

- .github/workflows/e2e-dev.yml
- .github/workflows/nightly.yml
Implements a fix for the nightly job, which was broken after https://github.com/dhis2/line-listing-app/pull/374 was merged.
---
1. Will (hopefully) avoid the Cypress out-of-memory issue on CI
---
When working on https://github.com/dhis2/line-listing-app/pull/374 I tweaked a lot of things to reduce the likelyhood of seeing the `Missing browserCriClient in connectToNewSpec` error occur during the Cypress e2e test run.
One of the things I did was to start working with a local copy of the `e2e-prod` GitHub workflow. I did this because the shared version of this workflow from data-visualizer is using a pre-baked Docker container in which the error was occuring very frequently. Not using that container made the error occur less frequently.
Whilst working on …
> fix: use local copy of e2e-dev in nightly github workflow

- cypress.config.js
- cypress/support/util.js
based on https://github.com/dhis2/maps-app/pull/2720
We seem to get random failures pretty regularly and they are often caused by slow instance. This will increase the default timeout for all DOM activity, which I hope will alleviate some of this.
> chore: increase cypress default timeout for DOM activity

- .github/workflows/nightly.yml
Enables manual runs ([more info](https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow))
Changes the time to 5am UTC (7am CEST)
> chore: nightly workflow - enable manual runs and change scheduled time

- .github/workflows/nightly.yml
Disable for July as the tests are failing due to slow instances and nobody is around to look into it.
> chore: disable nightly for now

- src/components/Visualization/Visualization.js
Implements [DHIS2-15465](https://dhis2.atlassian.net/browse/DHIS2-15465)
---
1. Ensure pagination component does not exceed scroll container width
---
[DHIS2-15465]: https://dhis2.atlassian.net/browse/DHIS2-15465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: always have the full pagination in view

- .github/workflows/dhis2-verify-app.yml
Send alert to the analytics-bot slack channel if release is successful.
Also, both the success and failure bot messages will include the app version in the message.
> chore: add slack success message for release

- .github/workflows/dhis2-verify-app.yml
Currently there are release messages every time there is a push to master and the release step succeeds. But the release step succeeds even if there is no actual release (e.g chores, docs etc). Therefore, we need to check the commit message to ensure it was an actual release.
> chore: only run the release-success and release-failure gh workflow jobs on release commits

- src/AppWrapper.js
The interpretations access check needs the list of authorities
> fix: authorities is needed for the interpretation access check [DHIS2-15964]

- .github/workflows/e2e-prod.yml
1. restore test.e2e instances for Cypress testing
---
Now that test.e2e instances are working again, use those instead of debug
> test: use test.e2e instances for Cypress testing

- cypress/helpers/transfer.js
- cypress/integration/conditions/optionSetCondition.cy.js
- cypress/integration/table.cy.js
- src/components/App.js
- src/components/Dialogs/Conditions/OptionSetCondition.js
- src/components/DownloadMenu/useDownload.js
- src/components/Visualization/useAnalyticsData.js
- src/modules/__tests__/conditions.spec.js
- src/modules/conditions.js
This requires a backend fix.
Fixes [DHIS2-15771](https://dhis2.atlassian.net/browse/DHIS2-15771)
Fixes [DHIS2-16181](https://dhis2.atlassian.net/browse/DHIS2-16181)
**Requires [DHIS2-15775](https://dhis2.atlassian.net/browse/DHIS2-15775)**
---
1. lookup option set option labels correctly in the table rows
2. show the correct name in the layout chip tooltips
3. refactor how the metadata for option sets is stored in Redux
---
Options for different option sets can use the same `code`, which is what is returned in the rows in the analytics response.
The previous way of looking up the label to display in the table simply tried to find a metadata object whom `code` matches the value for the option set in the response's rows.
This cause to display the wrong label when different option sets are …
> fix: handle options with non-unique codes across optionsets (DHIS2-15771)

- .github/workflows/dhis2-verify-app.yml
- cypress.config.js
- jest.config.js
- package.json
- yarn.lock
- send jest test results to report portal dashboard
- send cypress test results to report portal dashboard
- Move jest configs out of packages.json and put it inside new jest.conf.js file
- Filter reportportal launches by dhis2 version before merge (https://github.com/dhis2/agent-js-cypress/pull/1)
> chore: send test results to reportportal dashboard

- cypress/helpers/fileMenu.js
- cypress/integration/save.cy.js
Fixes [DHIS2-16154](https://dhis2.atlassian.net/browse/DHIS2-16154)
**Requires https://github.com/dhis2/analytics/pull/1593**
---
1. bump analytics dep with the actual fix
2. add some Cypress tests for File Menu rename
---
The rename feature stopped working when support for deprecated PATCH request format was removed.
`json+patch` format is required for PATCH requests now.
The implementation for File Menu rename and update of custom calculations is in `analytics` (see linked PR).
This PR adds some tests for the File Menu rename feature.
---
-   [x] Update docs
-   [x] KFMT
-   [x] update dep once analytics PR [1593](https://github.com/dhis2/analytics/pull/1593) is merged
[DHIS2-16154]: https://dhis2.atlassian.net/browse/DHIS2-16154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmND …
> test: add tests for error when renaming a saved visualization (DHIS2-16154)

- cypress.config.js
Not in JIRA
---
1. Stop uploading videos of passing tests
1. The test suite should still pass
2. The test suite should not crash because it is trying to delete a file
3. When reviewing the cypress test run log we should see that no video was upload (unless there was a failing test)
> chore: only upload videos for failing cypress tests

- cypress/helpers/period.js
- cypress/integration/conditions/dateConditions.cy.js
- cypress/integration/table.cy.js
- cypress/integration/timeDimensions.cy.js
No JIRA
Fixes issues related to the yearly bump in the database.
Basically turns things like `1991` to "this year minus 33" (i.e. 2024-33=1991) for data that was unexpectedly bumped in the demo db.
> test: dynamic offset for years

- src/components/MainSidebar/InputPanel/InputOption.js
- src/components/MainSidebar/InputPanel/InputOption.module.css
- src/components/MainSidebar/ProgramDimensionsPanel/ProgramSelect.module.css
- src/components/MainSidebar/ProgramDimensionsPanel/StageSelect.js
This PR adjusts the design of the input option component:
- moves `radio` to share line with header text, to reduce indent
- use custom ultra-dense `label` for stage selector, removing use of `prefix` and allowing more horizontal space.
---
Before:
After:
> fix: adjust input option design

- jest.config.js
- src/components/Layout/__tests__/__snapshots__/ChipBase.spec.js.snap
A recent change to the jest configuration caused only the tests in src/modules to be run.
As a result of this, some component test snapshots were no longer valid when the new chip design was released.
> test: first test regex path that was filtering out component jest tests

- src/components/Dialogs/PeriodDimension/PeriodDimension.js
- src/components/Dialogs/PeriodDimension/StartEndDate.js
Fixes bug where Period Dimension doesn't recognize the start/end date that has been selected for a time dimension
Perhaps the `extractDimensionIdParts` should be renamed, since it is also used to get the selected item for the dimension?
> fix: extract the start-end-date part of the item id

- .github/workflows/dhis2-verify-app.yml
It is useful to see the release notes in the slack channel for a quick reference as to what was released.
The commit message in the "chore(release)" commit includes the release notes, so hopefully it will display nicely.
This is an example of what it will look like (except obviously it will say "Line Listing app":
> chore: include release notes in slackbot message

- public/push-analytics.json
Related to [DHIS2-15367](https://dhis2.atlassian.net/browse/DHIS2-15367) in JIRA and push-analytics [PR#10](https://github.com/dhis2/push-analytics/pull/10)
---
1. Adds a JSON file with scrape instructions which push-analytics can use to convert a dashboard item for this app.
---
[DHIS2-15367]: https://dhis2.atlassian.net/browse/DHIS2-15367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(push-analytics): add push analytics instructions

- .github/workflows/dhis2-verify-app.yml
This PR introduces the capability to trigger Cypress tests in line-listing-app via the **`repository_dispatch`** event from the DHIS2 core repository. It's part of an initiative to enhance our testing processes by allowing on-demand and automated cross-repository testing and enabling the DHIS2 core to directly request Cypress test execution in this app.
Implemented handling for `repository_dispatch` with the event type `cypress-test-trigger`.
> chore: implement handling for DHIS2 core-triggered dispatch events

- package.json
- src/components/Dialogs/FixedDimension.js
- yarn.lock
Implements [DHIS2-15000](https://jira.dhis2.org/browse/DHIS2-15000)
**Requires https://github.com/dhis2/analytics/pull/1664**
---
1. Pass `displayNameProp` to `OrgUnitDimension` to enable short name to work
---
-   [ ] Cypress tests
-   [ ] Update docs
-   [ ] Manual testing
[DHIS2-15000]: https://dhis2.atlassian.net/browse/DHIS2-15000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: system / user setting for display name not respected in Org Unit tree (DHIS2-15000)

- public/push-analytics.json
This PR removes `&` pre- and suffixes from `modifyDownloadUrl` search and replace strings in the push-analytics.json instructions file. These `&`s are problematic when the query parameter being replaced is the first or last query parameter present.
Push analytics now sanitises the search and replace strings, so the previous push-analytics file will work correctly as well. As such there is no rush to merge in this PR.
> chore: remove & pre- and suffixes from modifyDownloadUrl search and replace strings

- .github/workflows/e2e-dev.yml
- README.md
- cypress/integration/createEvent.cy.js
- cypress/integration/eventStatus.cy.js
- cypress/integration/legendSet.cy.js
- cypress/integration/programDimensions.cy.js
- cypress/integration/table.cy.js
- cypress/integration/timeDimensions.cy.js
- cypress/plugins/excludeByVersionTags.js
- d2.config.js
- src/__tests__/cypressGetExcludedTags.spec.js
- src/components/Dialogs/FixedDimension.js
- src/components/MainSidebar/YourDimensionsPanel/useYourDimensions.js
- src/components/Visualization/useAnalyticsData.js
- src/modules/options/lineListConfig.js
- src/reducers/ui.js
Implements [DHIS2-17209](https://dhis2.atlassian.net/browse/DHIS2-17209)
---
1. Bumps the min version to `2.39` and removes all corresponding toggles, tests and references to `2.38`
---
The PR removes all references to 2.38 and sets the min version to 2.39. It was decided in a recent meeting that this should bump the major version.
---
Only supported on 2.39 and above
---
-   [x] Figure out what type of release this should be (major, minor, patch)
[DHIS2-17209]: https://dhis2.atlassian.net/browse/DHIS2-17209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: bump Line Listing to mininum version 2.39 (DHIS2-17209)

- cypress/integration/programDimensions.cy.js
- src/components/MainSidebar/ProgramDimensionsPanel/ProgramDimensionsPanel.js
Implements [DHIS2-17412](https://dhis2.atlassian.net/browse/DHIS2-17412)
---
1. Clean up code for determining how/when to use `stageId`
---
There seems to have been either a copy/paste error or a conflict resolution slip up in a previous PR for determining how/when to use ’stageId’ in the ’StageFilter’. 
There are two separate flows - event/enrollment and TE. However there was code referencing e.g. event with in the TE flow, which is obviously incorrect. This has now been cleaned up so the stage filter works as expected.
---
-   [x] Update docs
---
_event_
_enrollment_
_tracked entity_
[DHIS2-17412]: https://dhis2.atlassian.net/browse/DHIS2-17412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: enrollment line list filter for program stage not working (DHIS2-17412)

- package.json
- yarn.lock
Implements [DHIS2-16018](https://dhis2.atlassian.net/browse/DHIS2-16018)
**Requires https://github.com/dhis2/analytics/pull/1669**
---
1. Bumps Analytics to the version that contains the fix
---
---
Note that the url is missing the instance name when used on Netlify:
When uploaded as a custom version to the instance directly it works as expected though, as seen below: 
[DHIS2-16018]: https://dhis2.atlassian.net/browse/DHIS2-16018?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: favourite link is missing the app name (DHIS2-16018)

- .github/dependabot.yml
Added a group to group together all security updates. Also, the exclude-pattern was missing wildcards so it didn't work.
> chore: add group for security updates to dependabot config

- cypress/integration/table.cy.js
- src/modules/tableValues.js
Implements [DHIS2-16717](https://dhis2.atlassian.net/browse/DHIS2-16717)
---
1. Change time format to 24h
---
Previously the `hh` time format was used in `moment.js`, which is using a 12h clock, causing 11am and 11pm to look identical - `11:00`. 
Switching to the `HH` time format, that uses a 24h clock, means 11pm will be outputted as `23:00` instead.
---
-   [ ] Update docs
---
_api docs (https://momentjs.com/docs/)_
_before_
_after_
[DHIS2-16717]: https://dhis2.atlassian.net/browse/DHIS2-16717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: hh:mm time format ambiguous (DHIS2-16717)

- package.json
- yarn.lock
Implements [DHIS2-XXXX](https://dhis2.atlassian.net/browse/DHIS2-XXXX)
---
1. fix bug that prevents LL to show in dashboard
---
Originally reported by Yuri.
The issue was introduced in version 101.0.4 where `cli-app-scripts` was updated to version 11.2.2.
The issue is related to some CSS rule which causes the LL table to be hidden when used in a dashboard item.
The fix is in cli-app-scripts where the plugin shell is built.
---
-   [ ] Cypress tests
---
Before:
After:
> fix: remove CSS that prevents LL from showing in dashboard

- cypress/integration/options.cy.js
- src/modules/tableValues.js
- src/modules/timeDimensions.js
- yarn.lock
Implements [DHIS2-17855](https://dhis2.atlassian.net/browse/DHIS2-17855)
---
1. display the right format for time dimensions
---
From 42 all time dimensions are passed as `DATETIME` but with the exception of `lastUpdated` they don't have the time part set.
These time dimensions should be formatted as date.
For this we need a mapping in the LL app in order to override the `DATETIME` valueType and format the values correctly.
Some version checks in Cypress tests have been updated after the recent releases.
---
---
Before:
After:
[DHIS2-17855]: https://dhis2.atlassian.net/browse/DHIS2-17855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: display the right format for time dimensions (DHIS2-17855)

- package.json
- yarn.lock
Fixes [DHIS2-17707](https://dhis2.atlassian.net/browse/DHIS2-17707)
**Requires https://github.com/dhis2/analytics/pull/1690**
---
1. update `analytics` dependency with fix for period selector validation
---
See https://github.com/dhis2/analytics/pull/1690 for a detailed description.
---
[DHIS2-17707]: https://dhis2.atlassian.net/browse/DHIS2-17707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: bump analytics with period selector validation fix (DHIS2-17707)

- cypress.config.js
- cypress/integration/mainSidebar.cy.js
- src/components/MainSidebar/MainSidebar.module.css
- src/modules/localStorage.js
- src/modules/ui.js
No JIRA ticket
---
1. Ensures the width written to local storage is always an integer
---
I opted to sanitise both on read and write. This covers an edge case for users who have a broken app already, with an invalid width in local storage.
---
---
> fix: sanitize width before reading and writing to local storage

- src/components/MainSidebar/MainSidebar.module.css
- src/components/MainSidebar/useResizableAccessorySidebar.js
Implements [DHIS2-17923](https://dhis2.atlassian.net/browse/DHIS2-17923)
---
1. allow grabbing the drag handle besides the resize handle
---
I've reduced the space on the left of the resize-handle. Before I used to have some transparent pixels there that would also trigger the interaction, as per the specs. Since those made the drag handle inaccessible with the mouse, I've had to remove most of it. Since the border is 1px and the resize-handle is 3 px, the resize-handle still "sticks out" by 1 px on the left. I've kept the 8 px on the right, so the interaction is still 10px wide. I think this is enough for users to trigger the interaction without too much effort. This does mean that the interaction area is now asymmetrical, which is probably  slightly odd, but still better than having a …
> fix: reduce resizehandle interaction area on left side [DHIS2-17923]

- jest.config.js
This PR disables ReportPortal integration when a PR is created by Dependabot, preventing 401 errors caused by missing API keys or secrets in these PRs.
> chore: skip ReportPortal integration for Dependabot PRs

- .github/workflows/verify-pr.yml
Use hardcoded dev version instead of relying on the analytics-dev instance to get this value
> chore: use hardcoded dev version for running e2e prod tests

- cypress.config.js
No JIRA issue available, 
Having `numTestsKeptInMemory` set to a low number can make local debugging using `cy:open`difficult. Normally you can hover over steps to see the state of the DOM in each one. However, when the number of tests in the current test file exceed the value of `numTestsKeptInMemory`, you well start seeing message saying `The snapshot is missing. Displaying current state of the DOM` for the first tests in the file.
After inspecting [the Cypress docs](https://docs.cypress.io/guides/references/configuration#Global), it turns out that the default behaviour is actually what we want:
> The number of tests for which snapshots and command data are kept in memory. `numTestsKeptInMemory` is set to `50` by default during `cypress open` and set to `0` by default during `cypress …
> chore: remove numTestsKeptInMemory from cypress config because default behaviour is better

- cypress/integration/pushAnalytics.cy.js
Implements [DHIS2-17868](https://dhis2.atlassian.net/browse/DHIS2-17868)
---
1. e2e test to check `push-analytics.json` exists and has the expected properties
2. e2e test to assert the file download mechanism used by push-analytics works
[DHIS2-17868]: https://dhis2.atlassian.net/browse/DHIS2-17868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: add e2e test to assert push-analytics prerequisites

- cypress/support/e2e.js
1.use enableAutoLogin for handling login correctly
---
The .action endpoint has been removed in 42.
The enableAutoLogin function from cypress-commands handles correctly the login for different instance versions.
> chore: use enableAutoLogin for handling Cypress login correctly

- package.json
- yarn.lock
Implements [DHIS2-19274](https://dhis2.atlassian.net/browse/DHIS2-19274)
**Requires https://github.com/dhis2/analytics/pull/1770**
---
1. Uses new version of @dhis2/analytics with fixes for hyperlinks in markdown editor and get-link helpers
2. Uses new version of @dhis2/cli-app-scripts to ensure page template has a base target set to `_top`
---
App and plugin can be tested on https://test.e2e.dhis2.org/analytics-42dev
[DHIS2-19274]: https://dhis2.atlassian.net/browse/DHIS2-19274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: ensure hyperlinks work when using the upcoming global shell [DHIS2-19274]

- src/components/App.js
Related to [DHIS2-19381](https://dhis2.atlassian.net/browse/DHIS2-19381) and [DHIS2-19387](https://dhis2.atlassian.net/browse/DHIS2-19387)
Pretty much the same changes for DV and maps:
https://github.com/dhis2/maps-app/pull/3508
https://github.com/dhis2/data-visualizer-app/pull/3375
https://github.com/user-attachments/assets/17ce549f-0fb8-4072-9dcb-f0033e4bd66b
[DHIS2-19381]: https://dhis2.atlassian.net/browse/DHIS2-19381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-19387]: https://dhis2.atlassian.net/browse/DHIS2-19387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix:  restore navigation between line lists using the browser address bar [DHIS2-19387]

- cypress/integration/conditions/optionSetCondition.cy.js
- cypress/integration/fileMenu.cy.js
- cypress/integration/options.cy.js
- cypress/integration/orgUnitDimension.cy.js
- cypress/integration/save.cy.js
The previous PR which implemented the cleanup of all created visualization during Cypress test runs had a bug in the extraction of the ids which prevented those visualizations from being deleted.
The regexp is fixed here to correctly extract the id from the URL.
All the names used for the saved visualization have been shortened and they should be unique.
The full date and time is being replaced with the epoch.
---
Add _N/A_ to items that are not applicable.
> chore: fix test visualizations cleanup in Cypress

- src/components/Visualization/StartScreen.js
Implements [DHIS2-18470](https://dhis2.atlassian.net/browse/DHIS2-18470)
---
1. use correct icon in Most viewed list
---
The icon used in the Most viewed list was the default column chart visualization.
The reason was that the visualization objects returned in the most viewed list didn't have the `type` so the icon used was the default fallback icon (colum chart visualization).
---
---
Before:
After:
[DHIS2-18470]: https://dhis2.atlassian.net/browse/DHIS2-18470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: use correct icon in most viewed list (DHIS2-18470)

- .github/workflows/verify-pr.yml
- cypress/integration/options.cy.js
- src/__tests__/cypressGetExcludedTags.spec.js
- src/components/VisualizationOptions/VisualizationOptionsManager.js
- src/modules/options/config.js
- src/modules/options/lineListConfig.js
Implements [DHIS2-19609](https://dhis2.atlassian.net/browse/DHIS2-19609)
and [DHIS2-19574](https://dhis2.atlassian.net/browse/DHIS2-19574)
1. Remove version toggles in tests and code for 2.39 support
2. Use the branch of the `workflow` repo with the gh action that runs the cypress tests that uses format `anly-e2e-4x`
---
[DHIS2-19609]: https://dhis2.atlassian.net/browse/DHIS2-19609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DHIS2-19574]: https://dhis2.atlassian.net/browse/DHIS2-19574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: remove 39 support and use anly-e2e-4x format for cypress test instances
